### ISSUE TITLE
maestre: libbz2.so.1.0 not found

### ISSUE THREAD

**Issue by menzel** [polyactis/Accucopy#16]
maestre does not find the libbz2.so.1.0 and fails with the usual lib not found error message:

/opt/accucopy/maestre: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

Even though I installed libbz2 for the current conda environment as well as on the system:

conda install -c conda-forge bzip2
yum install bzip2-libs

**Comment by fanxinping** [comment]
Hi,
I think the reason is that you have installed bzip shared library in the conda env but it hasn't been added to the shared library search path.
You can find where the `libbz2.so.1.0` is and add it to the env variable `LD_LIBRARY_PATH`. 
For example:
I find `libbz2.so.1.0` in `/y/home/fanxp/.local/anaconda3/envs/deep/lib`, and I have two method to add it
1.`LD_LIBRARY_PATH=/y/home/fanxp/.local/anaconda3/envs/deep/lib:$LD_LIBRARY_PATH Accucopy/main.py .......`
2. 
   ```bash
export LD_LIBRARY_PATH=/y/home/fanxp/.local/anaconda3/envs/deep/lib:$LD_LIBRARY_PATH
Accucopy/main.py .......
   ```
Method `1` is recommended and try mehtod `2` if method `1` is not work. Method `2` will pollute the shared library search path in the current user's shell, and some dynamically linked programs will failed if some shared library in the `/y/home/fanxp/.local/anaconda3/envs/deep/lib` conflict with those. If that occur, please logout and login to refresh `LD_LIBRARY_PATH` to default. Besides, using `-Wl,-rpath` flag when compile will store `libbz2.so.1.0` searching path into the program and `LD_LIBRARY_PATH` is no longer needed if you familiar with compiler flag and Makefile.

Accucopy is hard to compile and using Docker image or Singulairty image is recommended.

**Comment by menzel** [comment]
Thanks for the fast replay and fixing my conda issues. It worked now, but hangs with the next library problem (libhdf5_cpp.so.100).

I'll try the docker image later. Unfortunately, your domain yfish is marked as suspicious in our network and I cannot access it from work.
